name: Deploy to Test Server
 
on:
  push:
    branches: [main]
    paths-ignore:
      - '**.md'
      - '.gitignore'
  workflow_dispatch:
 
jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ${{ secrets.FTP_PATH }}
          protocol: ftp
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/src/**
            **/temp/**
            .env
            .gitignore
            package.json
            package-lock.json
            vite.config.js
            vite.svg
            **/*.md
 
